version: "3.9"

services:
  redis:
    image: redis:7.0.5-bullseye
    ports:
      - "6379:6379"

  api:
    restart: "no"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/
    ports:
      - "8080:8080"
    networks:
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - redis
    stdin_open: true
    tty: true
