version: "3.9"

x-txt-encoder:
  &custom_txt_encoder
  restart: "no"
  command: txt_encoder
  env_file:
    - .env
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/opt/
  networks:
    - default
  dns:
    - 8.8.8.8
    - 8.8.4.4
  depends_on:
    - redis

x-img-encoder:
  &custom_img_encoder
  restart: "no"
  command: img_encoder
  env_file:
    - .env
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/opt/
  networks:
    - default
  dns:
    - 8.8.8.8
    - 8.8.4.4
  depends_on:
    - redis

services:
  redis:
    image: redislabs/redisearch:2.8.4
#    image: redis/redis-stack:edge-arm64
    ports:
      - "6379:6379"
#    command: redis-server --maxmemory 16gb --maxmemory-policy allkeys-lru --loadmodule /usr/lib/redis/modules/redisearch.so
    command: redis-server --maxmemory 7gb --maxmemory-policy allkeys-lru --loadmodule /usr/lib/redis/modules/redisearch.so

  txt_encoder_0:
    <<: *custom_txt_encoder
    ports:
      - "80:80"
      - "443:443"
    environment:
      - QUEUE_ID=0

  txt_encoder_1:
    <<: *custom_txt_encoder
    ports:
      - "81:80"
      - "444:443"
    environment:
      - QUEUE_ID=1

  txt_encoder_2:
    <<: *custom_txt_encoder
    ports:
      - "82:80"
      - "445:443"
    environment:
      - QUEUE_ID=2

  img_encoder_0:
    <<: *custom_img_encoder
    ports:
      - "83:80"
      - "446:443"
    environment:
      - QUEUE_ID=0

  img_encoder_1:
    <<: *custom_img_encoder
    ports:
      - "84:80"
      - "447:443"
    environment:
      - QUEUE_ID=1

  img_encoder_2:
    <<: *custom_img_encoder
    ports:
      - "85:80"
      - "448:443"
    environment:
      - QUEUE_ID=2

  api:
    restart: "no"
    command: api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/dl_models:/opt/app/dl_models
      - ./app/input:/opt/app/input
      - ./app/output:/opt/app/output
      - ./app/routers:/opt/app/routers
      - ./app/services:/opt/app/services
    ports:
      - "8080:8080"
    networks:
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - redis
    stdin_open: true
    tty: true
